name: Compile Mod
on:
  release:
    types:
      - created

permissions:
  contents: write
  id-token: write
  pages: write
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: ls -R
        working-directory: ${{ github.workspace }}
      - run: 7z a ${{ github.event.repository.name }}.zip ${{ github.workspace }}
      - uses: ncipollo/release-action@v1.13.0
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: ${{ github.event.repository.name }}.zip
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
